Models/LogViewModel.cs
using System;
using System.Collections.Generic;
using gzDAL.Models;

namespace gzWeb.Admin.Models
{
    public class LogEntryViewModel
    {
        public LogEntryViewModel(LogEntry entry)
        {
            Id = entry.Id;
            Application = entry.Application;
            Logged = entry.Logged;
            Level = entry.Level;
            Message = entry.Message;
            UserName = entry.UserName;
            ServerName = entry.ServerName;
            Port = entry.Port;
            Url = entry.Url;
            Https = entry.Https;
            ServerAddress = entry.ServerAddress;
            RemoteAddress = entry.RemoteAddress;
            Logger = entry.Logger;
            CallSite = entry.CallSite;
            Exception = entry.Exception;

            Source = entry.Application + "::" + (entry.Url.Contains(".logger") ? "Client" : "Server");
            ShortMessage = entry.Message.Length > 105
                                   ? entry.Message.Substring(0, 50) + " ... " + entry.Message.Substring(entry.Message.Length - 50, 50)
                                   : entry.Message;
        }

        public int Id { get; set; }
        public string Application { get; set; }
        public DateTime Logged { get; set; }
        public string Level { get; set; }
        public string Message { get; set; }
        public string UserName { get; set; }
        public string ServerName { get; set; }
        public string Port { get; set; }
        public string Url { get; set; }
        public bool Https { get; set; }
        public string ServerAddress { get; set; }
        public string RemoteAddress { get; set; }
        public string Logger { get; set; }
        public string CallSite { get; set; }
        public string Exception { get; set; }

        public string Source { get; private set; }
        public string ShortMessage { get; private set; }
    }

    public class LogViewModel
    {        
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public string LogLevel { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string UserSearchText { get; set; }
        public List<LogEntryViewModel> LogEntries { get; set; }
    }

}

Controllers/LogsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using gzDAL.Models;
using gzWeb.Admin.Models;

namespace gzWeb.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LogsController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public LogsController()
        {
            // TODO: (xdinos) inject
            _dbContext = new ApplicationDbContext();
        }

        // GET: Admin/Logs
        public ActionResult Index(int page = 1, int pageSize = 20, string logLevel = null, DateTime? fromDate = null, DateTime? toDate = null, string userSearchText=null)
        {
            IQueryable<LogEntry> logEntries = _dbContext.LogEntries;

            if (!String.IsNullOrEmpty(logLevel))
                logEntries = logEntries.Where(x => x.Level == logLevel);

            var now = DateTime.Now;
            if (!fromDate.HasValue)
                fromDate = now.AddMonths(-1);

            if (!toDate.HasValue)
                toDate = fromDate.Value.AddMonths(1);

            logEntries = logEntries.Where(x => x.Logged >= fromDate.Value && x.Logged <= toDate.Value);
            if (!String.IsNullOrEmpty(userSearchText))
                logEntries = logEntries.Where(x => x.UserName.Contains(userSearchText) || x.Message.Contains(userSearchText));

            var totalPages = (int)Math.Ceiling((float)logEntries.Count() / pageSize);

            return View("Index", new LogViewModel
                                 {
                                         CurrentPage = page,
                                         TotalPages = totalPages,
                                         LogLevel = logLevel,
                                         FromDate = fromDate.Value,
                                         ToDate = toDate.Value,
                                         UserSearchText = userSearchText,
                                         LogEntries = logEntries.OrderByDescending(x => x.Logged)
                                                                .Skip(pageSize*(page - 1))
                                                                .Take(pageSize)
                                                                .ToList()
                                                                .Select(x => new LogEntryViewModel(x))
                                                                .ToList()
            });
        }

        public PartialViewResult GetEntry(int id)
        {
            return PartialView("_LogEntryModal", _dbContext.LogEntries.Single(x => x.Id == id));
        }
    }
}

Views/Logs/Index.cshtml
@model gzWeb.Admin.Models.LogViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="admin admin-logs">

    <article>
        <div class="container-fluid">
            <div class="admin-table">
                <div class="table-head">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="text-center">Logs History</h3>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 table-controls">
                            <div class="row">
                                @using (Html.BeginForm("Index", "Logs", FormMethod.Get))
                                {
                                    <div class="col-md-7 filters-form">
                                        <input type="hidden" name="page" value="1" />
                                        <input type="hidden" name="pageSize" value="20" />
                                        <div class="col-md-2 form-group date">
                                            <input type="date" class="form-control" placeholder="From Date" name="fromDate" value="@Model.FromDate.ToString("yyyy-MM-dd")" />
                                        </div>
                                        <div class="col-md-2 form-group date">
                                            <input type="date" class="form-control" placeholder="To Date" name="toDate" value="@Model.ToDate.ToString("yyyy-MM-dd")" />
                                        </div>
                                        <div class="col-md-2 form-group">
                                            <select name="logLevel" class="form-control">
                                                <option value="" @(String.IsNullOrEmpty(Model.LogLevel) ? "selected" : "")>All</option>
                                                <option value="Debug" @(Model.LogLevel == "Debug" ? "selected" : "")>Debug</option>
                                                <option value="Error" @(Model.LogLevel == "Error" ? "selected" : "")>Error</option>
                                                <option value="Fatal" @(Model.LogLevel == "Fatal" ? "selected" : "")>Fatal</option>
                                                <option value="Info" @(Model.LogLevel == "Info" ? "selected" : "")>Info</option>
                                                <option value="Trace" @(Model.LogLevel == "Trace" ? "selected" : "")>Trace</option>
                                                <option value="Warn" @(Model.LogLevel == "Warn" ? "selected" : "")>Warn</option>
                                            </select>
                                        </div>
                                        <div class="col-md-2 form-group">
                                            <input type="text" class="form-control" placeholder="user" name="userSearchText" value="@Model.UserSearchText" />
                                        </div>
                                        <div class="col-md-2 form-group">
                                            <button type="submit" class="btn-gz">Filter</button>
                                        </div>
                                    </div>
                                }

                                <div class="col-md-5 admin-pagination">
                                    <nav style="@(Model.TotalPages <= 1 ? "display:none;": "")">
                                        <ul class="pagination">
                                            <li class="@(Model.CurrentPage==1 ? "disabled": "")">
                                                <a href="@(Model.CurrentPage==1 ? "#":Url.Action("Index", "Logs", new { page = Model.CurrentPage - 1, logLevel = Model.LogLevel,  fromDate = Model.FromDate, toDate = Model.ToDate }))" aria-label="Previous">
                                                    <span aria-hidden="true">&laquo;</span>
                                                </a>
                                            </li>
                                            @for (var i = 1; i <= (int)Math.Min(Model.TotalPages, 6); i++)
                                            {
                                                <li class="@(Model.CurrentPage==i ? "active" : "")">
                                                    <a href="@Url.Action("Index", "Logs", new { page =i, logLevel = Model.LogLevel,  fromDate = Model.FromDate, toDate = Model.ToDate, userSearchText=Model.UserSearchText })" aria-label="@i">
                                                        <span aria-hidden="true">@i</span>
                                                    </a>
                                                </li>
                                            }
                                            <li class="@(Model.CurrentPage== Model.TotalPages ? "disabled": "")">
                                                <a href="@Url.Action("Index", "Logs", new { page = Model.CurrentPage + 1, logLevel = Model.LogLevel,  fromDate = Model.FromDate, toDate = Model.ToDate, userSearchText=Model.UserSearchText })" aria-label="Previous">
                                                    <span aria-hidden="true">&raquo;</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 table-interface">
                        <table class="table table-bordered">
                            <thead class="text-center">
                                <tr>
                                    <th class="col-md-1 text-center">Source</th>
                                    <th class="col-md-2 text-center">Date</th>
                                    <th class="col-md-1 text-center">Level</th>
                                    <th class="col-md-6 text-center">Message</th>
                                    <th class="col-md-2 text-center">User Name</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var entry in Model.LogEntries)
                                {
                                    <tr class="@entry.Level">
                                        <td class="text-center">@entry.Source</td>
                                        <td class="text-center">@entry.Logged</td>
                                        <td class="text-center">@entry.Level</td>
                                        <td class="">
                                            @{
                                                if (entry.Message.Length > 100)
                                                {
                                                    @(entry.Message.Substring(0, 50) + " ... " + entry.Message.Substring(entry.Message.Length - 50, 50))
                                                }
                                                else { @entry.Message }
                                            }
                                        </td>
                                        <td class="text-center">@entry.UserName</td>
                                        <td>
                                            <button type="button" class="btn-gz view-entry-btn" data-id="@entry.Id">Show Details</button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </article>

    <div class="modal fade" id="view-entry" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="view-entry-container">

            </div>
        </div>
    </div>

</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.view-entry-btn').click(function () {
                var url = "@Url.Action("GetEntry","Logs")"; // the url to the controller
                var id = $(this).attr('data-id'); // the id that's given to each button in the list
                $.get(url + '/' + id, function (data) {
                    $('#view-entry-container').html(data);
                    $('#view-entry').modal('show');
                });
            });
        });
    </script>
}

Views/Logs/_LogEntryModal.cshtml
@model gzDAL.Models.LogEntry

<div class="log-entry-modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title text-center" id="myModalLabel">Entry ID <b>#@Model.Id @Model.Application</b> at <b>@Model.Logged</b> - <b>@Model.Level</b></h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>Message: </b></span>
                        <span class="col-md-10">@Model.Message</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>UserName: </b></span>
                        <span class="col-md-10">@Model.UserName</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>ServerName: </b></span>
                        <span class="col-md-10">@Model.ServerName</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>Port: </b></span>
                        <span class="col-md-10">@Model.Port</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>Url: </b></span>
                        <span class="col-md-10">@Model.Url</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>Https: </b></span>
                        <span class="col-md-10">@Model.Https</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>ServerAddress: </b></span>
                        <span class="col-md-10">@Model.ServerAddress</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>RemoteAddress: </b></span>
                        <span class="col-md-10">@Model.RemoteAddress</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>Logger: </b></span>
                        <span class="col-md-10">@Model.Logger</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>CallSite: </b></span>
                        <span class="col-md-10">@Model.CallSite</span>
                    </li>
                    <li class="col-md-12">
                        <span class="col-md-2"><b>Exception: </b></span>
                        <span class="col-md-10">@Model.Exception</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    @*<div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>*@
</div>